<?php
// 1. Your Fact Database
$facts = [
		// --- THE ORIGINALS & CLASSICS ---
		"Bananas are berries, but strawberries aren't. Botanists clearly have a very specific sense of humor.",
		"Octopuses have three hearts. That is a lot of internal plumbing for an animal that can fit through a keyhole.",
		"The dot over the lowercase 'i' is called a tittle. It's a tiny, purposeful detail in the alphabet.",
		"The unicorn is the national animal of Scotland. They've always had an eye for the majestic and unique.",
		"Bees can recognize human faces. So be nice to them. You don't want to be on a hive's 'most wanted' list.",
		"Some turtles can breathe through their backside (cloacal respiration). It's a brilliant way to survive underwater during winter.",
		"Wombat poop is cube-shaped so it doesn't roll away. It's essentially nature's way of marking territory with blocks.",
		"Cats can't taste sweetness. They were designed to be pure predators, completely unimpressed by your sugar cravings.",
		"A snail can sleep for three years. It's not laziness; it's a very long-term commitment to rest.",
		"Lobsters taste with their legs. Imagine the sensory experience of every step being a potential appetizer.",
		"Your tongue knows exactly what every object in your room feels like without you even touching it. A strangely specific gift of spatial awareness.",
		"Sea otters hold hands while sleeping so they don't drift apart. It's a built-in safety protocol for the ocean.",
		"The word 'swims' looks the same upside down. A rare bit of perfect linguistic symmetry.",
		"Everything you smell is actually particles of that thing entering your nose. Yes, even in the locker room. Sorry about that.",
		"Ants can survive in a microwave by standing in the 'cold spots.' They are the ultimate resilient snacks.",
		"Your fingers prune in water to improve your grip. It's a brilliant 'wet-weather' feature for handling slippery objects.",
		"Rabbits can't puke. They are physically designed to commit 100% to whatever they decide to eat.",
		"The reason you can't tickle yourself is because your brain knows it's coming. You can't prank a system that's already two steps ahead of you.",
		"Honey never spoils. Archaeologists found 3,000-year-old honey that is still edible. Truly the eternal snack.",
		"Your skeleton is always wet. It's a slightly uncomfortable fact to carry around all day.",
		"A shrimp's heart is in its head. It gives a whole new meaning to 'having your heart in the right place.'",
		"There is a town in Norway where it has actually rained fish. A very literal version of sky-based seafood delivery.",
		"Sloths can hold their breath longer than dolphins. They aren't slow; they are masters of aquatic endurance.",
		"The average cloud weighs 1.1 million pounds. It's a feat of engineering that they stay suspended so effortlessly.",
		"If a tomato is a fruit, ketchup is technically a smoothie. A culinary classification crisis waiting to happen.",
		"You can't hum while holding your nose. Go ahead, try it. Still doesn't work.",
		"Sharks existed before trees. They are the original, time-tested models of the deep sea.",
		"Elephants think humans are 'cute,' similar to how we look at puppies. We are officially the pets of the animal kingdom.",
		"All swans in England technically belong to the King now. Even Steve. Steve is a total menace, and now he's His Majesty's problem.",
		"A single spaghetti noodle is called a 'spaghetto.' Use this at dinner to instantly confuse your friends.",
		"Vending machines are statistically more dangerous than sharks. Choose your snacks with a healthy dose of caution.",
		"Space smells like seared steak. The heavens are apparently more aromatic than we expected.",
		"Your liver can regenerate itself. It's a remarkable, self-healing feature of the human body.",
		"Jellyfish are 95% water. They are basically sentient, stinging puddles of the ocean.",
		"The longest recorded flight of a chicken is 13 seconds. It wasn't a long journey, but it was an honest effort.",
		"Cows have best friends and experience stress when separated. They were clearly designed with a social heart.",
		"Your nose can remember 50,000 different scents, yet it still struggles to find where you left your phone.",
		"Mount Everest grows about 4mm taller every year. It's still reaching for the sky.",
		"If you scream for 8 years, 7 months, and 6 days, you'd produce enough energy to heat one cup of coffee. Just use the stove.",

		// --- NEW BATCH: ANIMAL ODDITIES ---
		"A group of flamingos is called a 'flamboyance.' The naming department actually got that one right.",
		"A group of owls is called a 'parliament.' They look wise, but they mostly just discuss mice.",
		"A group of crows is a 'murder.' That seems a bit dramatic, even for them.",
		"A group of rhinos is called a 'crash.' Which is exactly what happens if you stand in their way.",
		"Platypuses don't have stomachs. Their esophagus goes straight to their intestines. Efficient, if a bit blunt.",
		"Koalas have fingerprints that are almost indistinguishable from humans. Don't let them frame you for a crime.",
		"A newborn giant panda is about the size of a stick of butter. It has a lot of growing to do.",
		"Butterflies taste with their feet. Imagine standing on a cupcake and knowing exactly how much frosting is on it.",
		"Squirrels plant thousands of new trees every year simply by forgetting where they hid their nuts.",
		"Pigs are incapable of looking up at the sky. They have to rely on your descriptions of the clouds.",
		"Woodpeckers wrap their tongues around their brains to act as shock absorbers. Genius-level engineering.",
		"A crocodile cannot stick its tongue out. It's literally attached to the roof of its mouth.",
		"Starfish don't have brains or blood. They're basically living, salty ornaments.",
		"The heart of a blue whale is the size of a bumper car. Its tongue weighs as much as an elephant.",
		"Horses and rats can't vomit. They are also members of the 'Total Commitment to Lunch' club.",
		"Hummingbirds are the only birds that can fly backwards. They're the stunt pilots of the garden.",
		"A housefly hums in the key of F. Next time one is buzzing, try to harmonize.",
		"Ostrich eyes are larger than their brains. They see everything, but they don't always know what to do about it.",
		"Dragonflies have six legs but cannot walk. They are built strictly for flight.",
		"An electric eel can generate a shock of up to 600 volts. That's a very spicy underwater noodle.",
		"Giraffes have the same number of neck vertebrae as humans (seven). Theirs are just significantly longer.",
		"A goat's pupils are rectangular. It gives them a panoramic view so they can see trouble coming from the sides.",
		"Reindeer eyeballs turn blue in winter to help them see in low light. Seasonal headlights.",
		"Tarantulas can survive for more than two years without food. They are the champions of 'waiting for the pizza to arrive.'",
		"Hippos produce their own 'blood sweat,' which is actually a natural sunscreen and antibiotic.",
		"Male seahorses are the ones who give birth. Nature's way of sharing the workload.",

		// --- NEW BATCH: FOOD & GEOGRAPHY ---
		"Apples float because they are 25% air. They're basically fruit-themed life preservers.",
		"The first carrots were purple. They were later bred to be orange to honor the Dutch Royal Family.",
		"Peanuts aren't nuts; they're legumes. Everything you know about snacks is a lie.",
		"Cashews grow on the bottom of 'cashew apples' and have toxic shells. Someone was very brave to try the first one.",
		"Russia has more surface area than Pluto. It's a big country, but Pluto has better views.",
		"There are no snakes in Hawaii, Iceland, Ireland, or New Zealand. Just in case you were planning a getaway.",
		"The Sahara Desert can actually experience snow. It's rare, but it happens when the weather gets confused.",
		"The Dead Sea is so salty that you can't sink in it. You just bob around like a human cork.",
		"Canada has more lakes than the rest of the world combined. They're definitely winning the freshwater game.",
		"There is a town in Nebraska called Monowi with a population of one. She is the mayor, the librarian, and the bartender.",
		"A day on Mercury lasts about 59 Earth days. Talk about a long shift.",
		"The Great Wall of China is not visible from the moon with the naked eye. That's a total myth.",
		"The driest place on Earth is in Antarctica, in an area called the Dry Valleys. No rain for millions of years.",
		"Istanbul is the only city in the world that sits on two continents (Europe and Asia).",
		"The Amazon rainforest produces about 20% of the world's oxygen. It's basically the planet's lungs.",

		// --- NEW BATCH: HUMAN BODY & BRAIN ---
		"Your brain is more active when you are sleeping than when you are watching TV.",
		"Human teeth are just as strong as shark teeth. We just don't use them to bite boats.",
		"Your nose and ears never stop growing. Gravity and cartilage are a persistent duo.",
		"The strongest muscle in the human body (relative to its size) is the masseter—the jaw muscle.",
		"You lose about 50 to 100 hairs a day. Most of them end up in your hairbrush or on your sweater.",
		"The human eye can distinguish about 10 million different colors. Most of which we just call 'blue-ish.'",
		"It takes about 20 seconds for a red blood cell to circle your entire body.",
		"Your body has enough iron in it to make a metal nail 3 inches long.",
		"You have no sense of smell when you are asleep. The 'smell of coffee' only wakes you up once you're already stirring.",
		"The space between your eyebrows is called the glabella. Now you know.",
		"Your heart beats about 100,000 times a day. It never takes a holiday.",
		"The small 'pocket' in your jeans was originally designed to hold a pocket watch.",
		"Humans are the only animals with chins. Think about that next time you look in the mirror.",
		"The average person spends about six months of their life waiting for red lights to turn green.",
		"You share a birthday with about 19 million other people. You're never truly celebrating alone.",

		// --- NEW BATCH: GENERAL WEIRDNESS ---
		"The lighter was invented before the match. Someone was really tired of using flint.",
		"The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion of the iron.",
		"Wycliffe Bible was the first English translation. Language changes, but the Word remains.",
		"A bolt of lightning contains enough energy to toast 100,000 slices of bread. One very fast breakfast.",
		"The world's oldest wooden wheel is over 5,000 years old. It's been a long road.",
		"The 'M's' on M&Ms are printed with edible 'ink' that doesn't dissolve in chocolate.",
		"The inventor of the Frisbee was turned into a Frisbee after he died (his ashes were molded into one).",
		"The first alarm clock could only ring at 4:00 AM. It was invented by someone who clearly hated sleeping in.",
		"Rubber bands last longer when they are refrigerated. Keep your office supplies in the crisper drawer.",
		"There are more possible iterations of a game of chess than there are atoms in the observable universe.",
		"The crack of a whip is actually a tiny sonic boom. The tip is moving faster than the speed of sound.",
		"The average person walks the equivalent of five times around the world in their lifetime.",
		"A jiffy is 1/100th of a second. Use it correctly next time you're running late.",
		"The scent of freshly cut grass is actually a plant's 'distress call.' You're smelling botanical panic.",
		"Vultures can fly for hours without flapping their wings. They are the masters of the thermal updraft.",
		"The thumb is the only finger that has its own pulse. Check it next time you're bored.",
		"The 'New Car Smell' is a cocktail of dozens of chemicals. It's essentially 'New Plastic and Glue' scent.",
		"Paper was invented in China around 105 AD. Before that, people had to write on much heavier things.",
		"A single bolt of lightning is five times hotter than the surface of the sun.",
		"There are 293 ways to make change for a dollar. If you have a lot of time and a lot of nickels.",
		"The electric chair was invented by a dentist. Make of that what you will.",
		"Bubble wrap was originally intended to be 3D wallpaper. It failed at that, but succeeded at being fun to pop.",
		"The word 'alphabet' comes from the first two letters of the Greek alphabet: Alpha and Beta.",
		"Barbie's full name is Barbara Millicent Roberts. She has a very formal life we know nothing about.",
		"The first commercial flight took place in 1914. It lasted 23 minutes and only had one passenger.",
		"A person could walk through all the tunnels in the New York City Subway system in about 24 hours (if they were very fast).",
		"A 'moment' was a medieval unit of time equal to 90 seconds. 'Wait a moment' used to mean a lot longer.",
		"The average person will eat about 35 tons of food in their lifetime. That's a lot of groceries.",
		"The dot on a question mark used to be a full 'Qo' (for Quaestio), which eventually shrank into the symbol we use today.",
		"The phrase 'the whole nine yards' might come from the length of ammunition belts in WWII aircraft.",
		"If you fold a piece of paper 42 times, it would be thick enough to reach the moon. (But you can't, so don't try).",
		"The Hawaiian alphabet only has 13 letters. It's a very efficient way to communicate.",
		"There are more life forms living on your skin than there are people on the planet.",
		"The 'high five' wasn't invented until 1977. People before then were just waving awkwardly, probably.",
		"The most common name in the world is Muhammad.",
		"A 'googol' is the number 1 followed by 100 zeros. It's a lot of zeros.",
		"The first person to be convicted of speeding was going 8 mph in a 2 mph zone. A true rebel.",
		"A snail's mouth is the size of a pinhead, but it can contain up to 25,000 teeth.",
		"The tongue of a blue whale is so large that 50 people could stand on it. But they probably shouldn't.",
		"The word 'lethologica' describes the state of not being able to remember the word you're looking for.",
		"You can't breathe and swallow at the same time. You're trying it now, aren't you?",
		"An adult human is made up of approximately 7 octillion atoms. You are very, very complex.",
		"The first YouTube video was uploaded in 2005. It was a guy at the zoo talking about elephant trunks.",
		"The 'USB' in USB stands for Universal Serial Bus. It's not a vehicle, though.",
		"There are about 60,000 miles of blood vessels in your body. If you laid them out, they'd circle the Earth twice.",
		"The smell of rain (petrichor) is caused by a bacteria in the soil called actinomycetes.",
		"The word 'clue' originally meant a ball of thread. It's a reference to the myth of Theseus and the Minotaur.",
		"The world's smallest mammal is the bumblebee bat. It weighs less than a penny.",
		"The king of hearts is the only king in a deck of cards without a mustache.",
		"A 'butt' was a traditional unit of volume for wine (about 126 gallons). So a 'buttload' is a very specific amount.",
		"The fingerprints of koalas are so human-like that they have been confused at crime scenes.",
		"A shrimp's heart is in its head. Its brain is also in its head, which makes for a very crowded skull.",
		"The Great Wall of China is about 13,171 miles long. That's a lot of bricks.",
		"The word 'set' has the most definitions of any word in the English language.",
		"A 'jiffy' is actually 10 milliseconds. Use it wisely.",
		"Your eyes blink about 20 times a minute. That's over 10 million blinks a year.",
		"The blue whale's call is the loudest sound made by any animal. It can be heard miles away.",
		"The most expensive book ever purchased was the Codex Leicester by Leonardo da Vinci.",
		"A human's ears and nose never stop growing throughout their lifetime.",
		"A person's height is usually determined by their father, while their weight is determined by their mother.",
		"The human body has enough fat to make seven bars of soap.",
		"The average person spends two weeks of their life kissing. A much better use of time than waiting for red lights.",
		"The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo.'",
		"The first orange was actually green. Orange oranges are a result of specific breeding.",
		"The strongest muscle in the human body is the tongue. (Depending on how you measure 'strong').",
		"A cat has 32 muscles in each ear. They use them to ignore you with extreme precision.",
		"A group of frogs is called an 'army.' They're ready for the lily pad wars.",
		"The longest word in the English language has 189,819 letters. It's a protein.",
		"A person's brain is about 75% water. Stay hydrated, stay smart.",
		"The word 'gymnasium' comes from the Greek word 'gymnos,' which means 'naked.'",
		"The first webcam was created to check a coffee pot without getting up from a desk.",
		"The Eiffel Tower was originally intended for Barcelona, but they turned it down.",
		"A group of porcupines is called a 'prickle.' It's the perfect name.",
		"The human heart can create enough pressure to squirt blood 30 feet. (Please don't test this).",
		"The word 'salary' comes from the Latin word for 'salt.' Roman soldiers were sometimes paid in salt.",
		"A 'blue moon' is the second full moon in a single calendar month. It's rare, but not blue.",
		"The first person to reach the South Pole was Roald Amundsen in 1911.",
		"A person's taste buds are replaced every two weeks. Your palette is always evolving.",
		"The world's largest desert is actually Antarctica. Deserts are defined by rainfall, not heat.",
		"The first computer mouse was made of wood. It had two wheels and a single button.",
		"A group of kangaroos is called a 'mob.' They're the tough guys of the outback.",
		"The word 'testify' comes from the Latin word for 'witness.'",
		"The average person has about 1,460 dreams a year. You just don't remember most of them.",
		"The first photograph ever taken was in 1826. It took 8 hours of exposure time.",
		"A person's skin is their largest organ. Treat it well.",
		"The first VCR was the size of a piano. Watching movies at home used to be a major commitment.",
		"The word 'oxymoron' is itself an oxymoron. It comes from the Greek words for 'sharp' and 'dull.'",
		"A group of jellyfish is called a 'smack.' Watch out for the sting.",
		"The human brain can store about 2.5 petabytes of information. That's a lot of memories.",
		"The first iPhone was released in 2007. It changed the world in a jiffy.",
		"A group of ravens is called an 'unkindness.' They have a reputation to uphold.",
		"The word 'robot' comes from the Czech word for 'forced labor.'",
		"The first text message was sent in 1992. It said 'Merry Christmas.'",
		"A person's fingernails grow faster on their dominant hand.",
		"The word 'climax' comes from the Greek word for 'ladder.'",
		"A group of lemurs is called a 'conspiracy.' They always look like they're up to something.",
		"The first YouTube video was only 18 seconds long. Simple beginnings.",
		"The word 'vaccine' comes from the Latin word for 'cow.'",
		"A group of ferrets is called a 'business.' They're very professional about their mischief.",
		"The first digital camera was created in 1975. It weighed 8 pounds.",
		"A person's eyes are the same size from birth to death. Your nose and ears, however, didn't get the memo.",
		"The word 'paranoia' comes from the Greek words for 'beside' and 'mind.'",
		"A group of giraffes is called a 'tower.' It's a very literal description.",
		"The first email was sent in 1971. It was sent from one computer to another in the same room.",
		"A person's hair is made of the same protein as their fingernails: keratin.",
		"The word 'sarcasm' comes from the Greek word for 'to tear flesh.' A bit aggressive, don't you think?",
		"A group of sharks is called a 'shiver.' It's what you do when you see one.",
		"The first 3D movie was released in 1922. It required two projectors and a lot of patience.",
		"A person's skeleton is completely replaced every 10 years. You are literally a new person.",
		"The word 'pajamas' comes from the Persian word for 'leg garment.'",
		"A group of squirrels is called a 'scurry.' It's the sound they make when they see you.",
		"The first crossword puzzle was published in 1913. It was a diamond shape.",
		"A person's stomach acid is strong enough to dissolve razor blades. (Once again, please don't test this).",
		"The word 'bonus' comes from the Latin word for 'good.'",
		"A group of tigers is called an 'ambush.' You won't see them coming.",
		"The first person to walk on the moon was Neil Armstrong in 1969. One small step, one giant leap.",
		"A person's blood makes up about 8% of their body weight.",
		"The word 'muscle' comes from the Latin word for 'little mouse.' (Because a moving bicep looks like a mouse under the skin).",
		"A group of whales is called a 'pod.' They're a tight-knit family.",
		"The first telephone call was made in 1876. 'Mr. Watson, come here, I want to see you!'",
		"A person's lungs have a surface area about the size of a tennis court.",
		"The word 'candidate' comes from the Latin word for 'white' (because Roman candidates wore white togas).",
		"A group of zebras is called a 'dazzle.' Their stripes really do the work.",
		"The first airplane was the Flyer, flown by the Wright brothers in 1903.",
		"A person's body contains enough carbon to lead about 9,000 pencils.",
		"The word 'whisky' comes from the Gaelic word for 'water of life.'",
		"A group of baboons is called a 'troop.' They're a disciplined bunch.",
		"The first television was demonstrated in 1926. It was a mechanical system.",
		"A person's brain uses about 20% of the body's total oxygen and energy.",
		"The word 'quarantine' comes from the Italian word for 'forty' (the number of days ships had to wait).",
		"A group of barracudas is called a 'battery.' They're a high-energy group.",
		"The first video game was 'Pong,' released in 1972. It was just two lines and a dot.",
		"A person's DNA is about 99.9% identical to every other human's DNA.",
		"The word 'silly' used to mean 'happy' or 'blessed.' How times have changed.",
		"A group of bears is called a 'sloth.' Which is confusing, given that there are also actual sloths.",
		"The first microwave oven was the 'Radarange,' released in 1947. It was over 5 feet tall.",
		"A person's body has about 5 million hair follicles. Most of them are too small to see.",
		"The word 'cliché' comes from the sound a printing plate made. It was a repetitive sound for a repetitive phrase.",
		"A group of cats is called a 'clowder.' A group of kittens is a 'kindle.'",
		"The first digital watch was the 'Pulsar,' released in 1972. It had a red LED display.",
		"A person's heart is about the size of their clenched fist.",
		"The word 'ambition' comes from the Latin word for 'going around' (as in, going around to get votes).",
		"A group of caterpillars is called an 'army.' They're on a mission to find a leaf.",
		"The first GPS satellite was launched in 1978. It helped us finally find our way.",
		"A person's eyebrows help keep sweat out of their eyes. A very practical design.",
		"The word 'panic' comes from the Greek god Pan, who was known for making loud noises to scare people.",
		"A group of dolphins is called a 'pod.' They're a very social group.",
		"The first dishwasher was invented in 1886 by Josephine Cochrane. She was tired of her servants breaking her china.",
		"A person's bones are about four times stronger than concrete.",
		"The word 'clue' originally meant a ball of thread. (Another reference to the myth of Theseus).",
		"A group of eagles is called a 'convocation.' They're a very formal bunch.",
		"The first electric light bulb was invented by Thomas Edison in 1879. (Or Joseph Swan, depending on who you ask).",
		"A person's body has about 2 to 5 million sweat glands.",
		"The word 'robot' was first used in a play in 1920. It was about artificial people.",
		"A group of eels is called a 'swarm.' Watch out for the spicy ones.",
		"The first credit card was the 'Diners Club' card, released in 1950. It was for people who forgot their wallets at dinner.",
		"A person's brain can process images in as little as 13 milliseconds.",
		"The word 'trivia' comes from the Latin for 'three ways' (where people would gather to chat).",
		"A group of falcons is called a 'cast.' They're a very talented group.",
		"The first handheld cell phone call was made in 1973. It was a very large phone.",
		"A person's body has about 100 trillion cells. You are a very large city of life.",
		"The word 'utopia' comes from the Greek for 'no place.'",
		"A group of gnats is called a 'cloud.' They're a very annoying group.",
		"The first 3D printer was created in 1984. It could print small plastic objects.",
		"A person's eyes can see a candle flame from 1.6 miles away in total darkness.",
		"The word 'gossip' comes from the Old English for 'godparent.' It meant someone you were close to.",
		"A group of gorillas is called a 'band.' They're a very musical group, in their own way.",
		"The first digital computer was the ENIAC, completed in 1945. It filled an entire room.",
		"A person's skin is replaced about 900 times in their lifetime.",
		"The word 'enthusiasm' comes from the Greek for 'possessed by a god.'",
		"A group of hippos is called a 'bloat.' It's a very descriptive name.",
		"The first modern Olympic Games were held in 1896 in Athens.",
		"A person's brain is more active at night than during the day.",
		"The word 'alphabet' comes from the first two letters of the Greek alphabet: Alpha and Beta.",
		"A group of hyenas is called a 'cackle.' They're a very laughing group.",
		"The first successful heart transplant was performed in 1967.",
		"A person's body has enough sulfur to kill all the fleas on an average dog.",
		"The word 'nostalgia' comes from the Greek for 'homecoming' and 'pain.'",
		"A group of iguanas is called a 'mess.' They're a very messy group.",
		"The first movie with sound was 'The Jazz Singer,' released in 1927.",
		"A person's lungs can hold about 6 liters of air.",
		"The word 'paradise' comes from the Persian for 'enclosed garden.'",
		"A group of jaguars is called a 'shadow.' You won't see them coming.",
		"The first person to fly solo across the Atlantic was Charles Lindbergh in 1927.",
		"A person's hair can grow about 6 inches a year.",
		"The word 'climax' comes from the Greek for 'ladder.'",
		"A group of leopards is called a 'leap.' They're a very jumping group.",
		"The first person to reach the North Pole was Robert Peary in 1909.",
		"A person's body has enough phosphorus to make about 2,200 match heads.",
		"The word 'sarcasm' comes from the Greek for 'to tear flesh.'",
		"A group of mice is called a 'mischief.' They're a very mischievous group.",
		"The first person to swim the English Channel was Matthew Webb in 1875.",
		"A person's body has enough potassium to fire a toy cannon.",
		"The word 'pajamas' comes from the Persian for 'leg garment.'",
		"A group of monkeys is called a 'troop.' They're a very disciplined group.",
		"The first person to climb Mount Everest was Edmund Hillary and Tenzing Norgay in 1953.",
		"A person's body has enough magnesium to make a small photograph.",
		"The word 'gymnasium' comes from the Greek for 'naked,' which is probably because the Greeks trained naked.",
		"A group of nightingales is called a 'watch.' They're a very observant group.",
		"The first person to sail around the world alone was Joshua Slocum in 1898.",
		"A person's body has enough iron to make a 3-inch nail.",
		"The word 'clue' originally meant a ball of thread.",
		"A group of parrots is called a 'pandemonium.' They're a very noisy group.",
		"The first person to go into space was Yuri Gagarin in 1961.",
		"A person's body has enough calcium to whitewash a small shed.",
		"The word 'set' has the most definitions of any word in the English language.",
		"KingNullboy's social security number is 43. Why is this public? Who knows. Why is it 43? Also unclear."
	];

// 2. Pick the first fact to show on page load
$initial_fact = $facts[array_rand($facts)];
?>

<div class="textbox" id="homepageFact" style="cursor: pointer; user-select: none; background-color: transparent; border: none;" title="Click for a new fact">
	<strong>Did you know?</strong><br>
	<span id="factText"><?php echo $initial_fact; ?></span>
</div>

<script>
	(function() {
		// Inject the PHP array into JavaScript
		const facts = <?php echo json_encode($facts); ?>;
		const factText = document.getElementById('factText');
		const factContainer = document.getElementById('homepageFact');

		if (factContainer && factText) {
			factContainer.addEventListener('click', function() {
				// Pick a random fact from the JS array
				const newFact = facts[Math.floor(Math.random() * facts.length)];
				// Update the text inside the span
				factText.innerText = newFact;
			});
		}
	})();
</script>
